---
- name: Create deploy user
  hosts: "{{ target }}"
  become: yes
  roles:
    - user

- name: Setup CONSUL
  hosts: "{{ target }}"
  remote_user: deploy
  gather_facts: yes
  roles:
    - system
    - postgresql
    - ruby
    - rails
    - ssl
    - email
    - queue
    - unicorn
    - nginx
    - memcached
    - timezone
    - capistrano
    